import 'package:app_my_app/data/repositories/chatbot/chatbot_repository.dart';
import 'package:app_my_app/data/repositories/sale_group/sale_group_repository.dart';
import 'package:app_my_app/features/chatbot/controller/chatbot_controller.dart';
import 'package:app_my_app/features/sale_group/controller/sale_group_controller.dart';
import 'package:app_my_app/features/shop/controllers/recommendation_controller.dart';
import 'package:get/get.dart';
import 'package:app_my_app/data/repositories/bonus_point/daily_checkin_repository.dart';
import 'package:app_my_app/data/repositories/brands/brand_repository.dart';
import 'package:app_my_app/data/repositories/categories/category_repository.dart';
import 'package:app_my_app/data/repositories/product/product_repository.dart';
import 'package:app_my_app/data/repositories/shop/shop_repository.dart';
import 'package:app_my_app/data/repositories/user/user_repository.dart';
import 'package:app_my_app/data/repositories/vouchers/ClaimedVoucherRepository.dart';
import 'package:app_my_app/features/bonus_point/controller/daily_checkin_controller.dart';
import 'package:app_my_app/features/personalization/controllers/address_controller.dart';
import 'package:app_my_app/features/personalization/controllers/user_controller.dart';
import 'package:app_my_app/features/shop/controllers/brand_controller.dart';
import 'package:app_my_app/features/shop/controllers/product/cart_controller.dart';
import 'package:app_my_app/features/shop/controllers/product/checkout_controller.dart';
import 'package:app_my_app/features/shop/controllers/product/favourite_controller.dart';
import 'package:app_my_app/features/shop/controllers/product/shop_controller.dart';
import 'package:app_my_app/features/shop/controllers/product/variation_controller.dart';
import 'package:app_my_app/features/voucher/controllers/voucher_controller.dart';
import 'package:app_my_app/utils/helper/network_manager.dart';
import '../data/repositories/authentication/authentication_repository.dart';
import '../data/repositories/bonus_point/mission_repository.dart';
import '../data/repositories/notification/notification_repository.dart';
import '../data/repositories/review/review_repository.dart';
import '../data/repositories/vouchers/VoucherRepository.dart';
import '../features/bonus_point/controller/mission_controller.dart';
import '../features/bonus_point/controller/reward_controller.dart';
import '../features/notification/controller/notification_controller.dart';
import '../features/personalization/controllers/update_name_controller.dart';
import '../features/review/controller/review_controller.dart';
import '../features/sale_group/controller/group_request_controller.dart';
import '../features/sale_group/controller/invite_group_controller.dart';
import '../features/setting/controllers/friend_list_controller.dart';
import '../features/setting/controllers/friend_requests_controller.dart';
import '../features/setting/controllers/user_list_controller.dart';
import '../features/shop/controllers/product/all_products_controller.dart';
import '../features/shop/controllers/product_controller.dart';
import '../features/shop/screens/all_products/all_product_controller.dart';
import '../features/suggestion/suggestion_repository.dart';

class GeneralBindings extends Bindings{
  @override
  void dependencies() {
    Get.put(AuthenticationRepository());
    Get.put(NetworkManager());
    Get.put(UserRepository());
    Get.put(UserController());
    Get.put(ProductRepository());
    Get.put(ProductSuggestionRepository());
    Get.put(ProductController());
    Get.put(AllProductsController());
    Get.put(AllProductController());
    Get.put(BrandRepository());
    Get.put(BrandController());
    Get.put(CategoryRepository());
    Get.put(ShopRepository());
    Get.put(ShopController());
    Get.put(FavouritesController());
    Get.put(VariationController());
    Get.put(CartController());
    Get.put(UpdateNameController());
    Get.put(CheckoutController());
    Get.put(AddressController());
    Get.put(VoucherRepository());
    Get.put(VoucherController());
    Get.put(ClaimedVoucherRepository());
    Get.put(NotificationRepository());
    Get.put(NotificationController());
    NotificationController.instance.updateUserNotifications();
    Get.put(ReviewRepository());
    Get.put(WriteReviewScreenController());
    Get.put(DailyCheckInRepository());
    Get.put(DailyCheckinController());
    Get.put(SaleGroupRepository());
    Get.put(SaleGroupController());
    Get.put(UserListController());
    Get.put(FriendRequestsController());
    Get.put(FriendListController());
    Get.put(InviteGroupController());
    Get.put(GroupRequestController());
    Get.put(MissionRepository());
    Get.put(MissionController());
    Get.put(RewardController());
    Get.put(ChatbotRepository());
    Get.put(ChatbotController());
    Get.put(RecommendationController());
  }
 static void deleteAllControllers() {
    // Các controller
    Get.delete<UserRepository>();
    Get.delete<UserController>();
    Get.delete<ProductRepository>();
    Get.delete<ProductSuggestionRepository>();
    Get.delete<ProductController>();
    Get.delete<AllProductsController>();
    Get.delete<BrandRepository>();
    Get.delete<BrandController>();
    Get.delete<CategoryRepository>();
    Get.delete<ShopRepository>();
    Get.delete<ShopController>();
    Get.delete<FavouritesController>();
    Get.delete<VariationController>();
    Get.delete<CartController>();
    Get.delete<UpdateNameController>();
    Get.delete<CheckoutController>();
    Get.delete<AddressController>();
    Get.delete<VoucherRepository>();
    Get.delete<VoucherController>();
    Get.delete<ClaimedVoucherRepository>();
    Get.delete<NotificationRepository>();
    Get.delete<NotificationController>();
    Get.delete<ReviewRepository>();
    Get.delete<WriteReviewScreenController>();
    Get.delete<DailyCheckInRepository>();
    Get.delete<DailyCheckinController>();
    Get.delete<SaleGroupRepository>();
    Get.delete<SaleGroupController>();
    Get.delete<UserListController>();
    Get.delete<FriendRequestsController>();
    Get.delete<FriendListController>();
    Get.delete<InviteGroupController>();
    Get.delete<GroupRequestController>();
    Get.delete<MissionController>();
    Get.delete<RewardController>();
    Get.delete<ChatbotRepository>();
    Get.delete<ChatbotController>();
    Get.delete<RecommendationController>();
  }

}
